spring:
  application:
    name: microservice-consumer-user-feign
server:
  port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
logging:
  level:
    org.panda.customer.user.feign.TestFeignClient: DEBUG
hystrix.command.default.execuiton.ioslation.thread.timeoutInMilliseconds: 5000
      