server:
  port: 7901
spring:
  application:
    name: microservice-provider-consul-client2
  http:
    multipart:
      max-file-size: 2000Mb #默认1M
      max-request-size: 2500Mb #默认10M
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        tags: version=1.0,author=qintao
        healthCheckPath: /info.json
        healthCheckInterval: 30s
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        ip-address: 127.0.0.1
        prefer-ip-address: true
security:
  basic:
    enabled: false