#management:
#  port: 8762
server:
  port: 8080
  
security:
  basic:
    enabled: true
  user:
    name: user
    password: 123
spring: 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kyo-qin/repo