#management:
#  port: 8762
spring:
  zipkin:
    base-url: http://localhost:11008
  sleuth:
    sampler:
      percentage: 1.0
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 8761
eureka:
#eureka 两个配置
  datacenter: cloud
  environment: product
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
#  instance:
#    metadata-map:
#      management.port: 8762