spring:
  application:
    name: microservice-consumer-user
  zipkin:
    base-url: http://localhost:11008
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true