server:
  port: 7900
spring:
  zipkin:
    base-url: http://localhost:11008
  sleuth:
    sampler:
      percentage: 1.0
#  jpa:
#    generate-ddl: false
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#  datasource:
#    platform: h2
#    schema: classpath:schema.sql
#    data: classpath:data.sql
  application:
    name: microservice-provider-user
  http:
    multipart:
      max-file-size: 2000Mb #默认1M
      max-request-size: 2500Mb #默认10M
security:
  basic:
    enabled: false
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.ota: DEBUG
eureka:
  client:
#    region:
#    healthcheck:
#      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    instance-id: ${spring.application.name}:${server.port}
#    metadata-map:
#      zone: ABC      # eureka可以理解的元数据
#      lilizhou: BBC  # 不会影响客户端行为
    lease-renewal-interval-in-seconds: 5